// Generated by https://quicktype.io

export interface Testigo {
  id:              string;
  createdAt:       string;
  updatedAt:       string;
  nombre:          string;
  apellido:        string;
  cedulaIdentidad: string;
  nacionalidad:    string;
  sexo:            string;
  telefono:        string;
}
